Console/BExIS.Web.Shell/Areas/DCM/BExIS.Modules.Dcm.UI/Controllers/Legacy/EasyUploadSheetDataStructureController.cs
using BExIS.Dcm.UploadWizard;
using BExIS.Dcm.Wizard;
using BExIS.IO.Transform.Validation.Exceptions;
using BExIS.Modules.Dcm.UI.Models;
using System;
using System.Web.Mvc;
using System.Web.Routing;

namespace BExIS.Modules.Dcm.UI.Controllers
{
    public class EasyUploadSheetDataStructureController : Controller
    {
        private EasyUploadTaskManager TaskManager;

        [HttpGet]
        public ActionResult SheetDataStructure(int index)
        {

            /* SKIP BECAUSE ONLY ONE SELECTION IS POSSIBLE

            TaskManager = (EasyUploadTaskManager)Session["TaskManager"];

            //set current stepinfo based on index
            if (TaskManager != null)
            {
                TaskManager.SetCurrent(index);

                // remove if existing
                TaskManager.RemoveExecutedStep(TaskManager.Current());
            }

            SelectSheetFormatModel model = new SelectSheetFormatModel();

            // when jumping back to this step
            // check if sheet format is selected
            if (TaskManager.Bus.ContainsKey(EasyUploadTaskManager.SHEET_FORMAT))
            {
                if (!String.IsNullOrEmpty(Convert.ToString(TaskManager.Bus[EasyUploadTaskManager.SHEET_FORMAT])))
                {
                    model.SelectedSheetFormat = TaskManager.Bus[EasyUploadTaskManager.SHEET_FORMAT].ToString();
                }
            }

            model.StepInfo = TaskManager.Current();
            */

            TaskManager = (EasyUploadTaskManager)Session["TaskManager"];

            if (TaskManager != null)
            {
                // set SHEET_FORMAT
                TaskManager.AddToBus(EasyUploadTaskManager.SHEET_FORMAT, "TopDown");
                TaskManager.Current().SetValid(true);

                if (TaskManager.Current().IsValid())
                {
                    TaskManager.GoToNext();
                    Session["TaskManager"] = TaskManager;
                    ActionInfo actionInfo = TaskManager.Current().GetActionInfo;
                    return RedirectToAction(actionInfo.ActionName, actionInfo.ControllerName, new RouteValueDictionary { { "area", actionInfo.AreaName }, { "index", TaskManager.GetCurrentStepInfoIndex() } });
                }
            }


            return PartialView(new SelectSheetFormatModel());

        }

        /*
         * Is called when the "next"-Button on the SheetDataStructure-View is pressed
         * */
        [HttpPost]
        public ActionResult SheetDataStructure(object[] data)
        {
            TaskManager = (EasyUploadTaskManager)Session["TaskManager"];
            SelectSheetFormatModel model = new SelectSheetFormatModel();
            model.StepInfo = TaskManager.Current();

            if (TaskManager != null)
            {
                TaskManager.Current().SetValid(false);

                if (TaskManager.Bus.ContainsKey(EasyUploadTaskManager.SHEET_FORMAT))  //Check if there is a Sheet Format on the bus
                                                                                      //it's only added to the bus if it's valid so there's no need to double check that
                {
                    TaskManager.Current().SetValid(true);
                }
                else
                {
                    model.ErrorList.Add(new Error(ErrorType.Other, "Please select a sheet format."));   //No Format selected yet
                }

                if (TaskManager.Current().valid == true) //Jump to the next step
                {
                    TaskManager.AddExecutedStep(TaskManager.Current());
                    TaskManager.GoToNext();
                    Session["TaskManager"] = TaskManager;
                    ActionInfo actionInfo = TaskManager.Current().GetActionInfo;
                    return RedirectToAction(actionInfo.ActionName, actionInfo.ControllerName, new RouteValueDictionary { { "area", actionInfo.AreaName }, { "index", TaskManager.GetCurrentStepInfoIndex() } });
                }
                else //Stay on the same page
                {
                    TaskManager.Current().SetStatus(StepStatus.error);

                    //reload model
                    model.StepInfo = TaskManager.Current();
                }
            }

            return PartialView(model);
        }

        /*
         * If a valid sheet format was submitted via the radio buttons,
         * add it to the bus
         * */
        [HttpPost]
        public ActionResult AddSelectedDatasetStructureToBus(string format)
        {

            SelectSheetFormatModel model = new SelectSheetFormatModel();

            EasyUploadTaskManager TaskManager = (EasyUploadTaskManager)Session["TaskManager"];


            if (!String.IsNullOrEmpty(format) && validateSheetFormat(format))
            {
                //Valid sheet format was selected, add it to the bus
                TaskManager.AddToBus(EasyUploadTaskManager.SHEET_FORMAT, format);
            }
            else
            {
                //No valid format was selected, display an error
                model.ErrorList.Add(new Error(ErrorType.Other, "Please select a sheet format."));
            }

            Session["TaskManager"] = TaskManager;


            //create Model
            model.StepInfo = TaskManager.Current();

            //Make sure the selected sheet is correctly displayed
            model.SelectedSheetFormat = format;

            //Stay on the same page
            return PartialView("SheetDataStructure", model);

        }

        #region private methods


        #region helper

        /* Check if a valid sheet format was selected
         * */
        private bool validateSheetFormat(string sheetFormat)
        {
            switch (sheetFormat)
            {
                case "TopDown":
                    return true;
                case "LeftRight":
                    return true;
                case "Matrix":
                    return true;
                default:
                    return false;
            }
        }

        #endregion

        #endregion
    }
}

Console/BExIS.Web.Shell/Areas/DCM/BExIS.Modules.Dcm.UI/Views/EasyUploadSheetDataStructure/SheetDataStructure.cshtml
@model BExIS.Modules.Dcm.UI.Models.SelectSheetFormatModel
@using Telerik.Web.Mvc.UI;
@using Telerik.Web.Mvc.Resources;
@using BExIS.Modules.Dcm.UI.Models;

@{
    string preselect = "";
    if (!String.IsNullOrEmpty(Model.SelectedSheetFormat))
    {
        preselect = "[value=" + Model.SelectedSheetFormat + "]";
    }
}

<script>
    $(document).ready(function () {
        //Destroy the handsontable from the next step (happens when clicking the "prev" button) because it's causing performance problems
        if (typeof hotActive != 'undefined') {
            if (hotActive) {
                hot.destroy();
                hotActive = false;
            }
        }

        var selectedValue = "@(preselect)";

        if (selectedValue.length > 0) {
            $("input:radio[name=sheetFormat]" + selectedValue).attr('checked', true);
        }
    });
</script>
<style>
    div.sheetSelect label > img {
        width: 100px;
    }

    div.sheetSelect label > input {
        display: none;
    }

        div.sheetSelect label > input + img {
            cursor: pointer;
            border: 2px solid transparent;
            margin-left: 20px;
            margin-right: 20px;
        }

        div.sheetSelect label > input:checked + img {
            border: 6px solid rgba(255, 165, 0, 0.7);
            border-radius: 4px;
            width: 140px;
            margin-left: 0px;
            margin-right: 0px;
        }
</style>

<div id="Step3" class="uploadWizardStep">

    <div class="uploadWizardStep_Main">
        <div class="uploadWizardStep_Header stepper">
            <h3>@Model.StepInfo.title</h3>
        </div>

        <div class="uploadWizardStep_Description stepper">
            <p>
                Your uploaded file has a specific structure, please select which one (red = variable names, green = data).
            </p>
        </div>

        <div class="uploadWizardStep_Content stepper">
            <div class="sheetSelect">
                <label>
                    <input type="radio" name="sheetFormat" value="TopDown" />
                    <img src="~/Areas/DCM/Images/DCM_SelectFileStructure/top-down.png">
                </label>
                <!--
                <label>
                    <input type="radio" name="sheetFormat" value="LeftRight" />
                    <img src="~/Areas/DCM/Images/DCM_SelectAreas/left-right.png">
                </label>

                <label>
                    <input type="radio" name="sheetFormat" value="Matrix" />
                    <img src="~/Areas/DCM/Images/DCM_SelectAreas/matrix.png">
                </label>
                    -->
            </div>
        </div>
    </div>

    <div class="uploadWizardStep_Error stepper">
        @if (Model != null && Model.ErrorList != null && Model.ErrorList.Count != 0)
        {
        <ul>
            @foreach (BExIS.IO.Transform.Validation.Exceptions.Error s in @Model.ErrorList)
                {
            <li>@s.ToString()</li>
                }
        </ul>
        }
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {

        $('input[type=radio][name=sheetFormat]').change(function () {
            if ($(this).val() != null && $(this).val() != '') {
                var SelectedSheetFormat = $(this).val();

                // send to bus
                $.post('@Url.Action("AddSelectedDatasetStructureToBus", "EasyUploadSheetDataStructure", new RouteValueDictionary { { "area", "DCM" } })', { format: SelectedSheetFormat }, function (response) {
                })
            }
        })
    });
</script>