Console/BExIS.Web.Shell/Areas/RPM/BExIS.Modules.Rpm.UI/old/Controllers/Legacy2/DataStructureSearchController.cs
using System;
using System.Web.Mvc;
using Telerik.Web.Mvc;
using BExIS.Dlm.Entities.DataStructure;
using BExIS.Dlm.Services.DataStructure;
using BExIS.Modules.Rpm.UI.Models;
using BExIS.IO.Transform.Output;
using BExIS.Modules.Rpm.UI.Classes;
using System.Collections.Generic;
using Vaiona.Web.Mvc.Models;
using Vaiona.Web.Extensions;
using Vaiona.Logging;
using Vaiona.Web.Mvc;
using Vaiona.Persistence.Api;
using System.Linq;

namespace BExIS.Modules.Rpm.UI.Controllers
{
    public class DataStructureSearchController : BaseController
    {
        public ActionResult Index()
        {
            ViewBag.Title = PresentationModel.GetViewTitleForTenant("Data Structure Search", this.Session.GetTenant());
            return View();
        }

        [GridAction]
        public ActionResult _dataStructureResultGridBinding(long[] previewIds, string searchTerms, bool structured = true, bool unstructured = true)
        {
            searchTerms = Server.UrlDecode(searchTerms);
            return View(new GridModel(new DataStructureResultsModel(previewIds, searchTerms, structured, unstructured).dataStructureResults));
        }

        [GridAction]
        public ActionResult _dataStructurePreviewGridBinding(long dataStructureId)
        {
            return View(new GridModel(new StructuredDataStructurePreviewModel(dataStructureId).VariablePreviews));
        }

        public ActionResult _dataStructurePreviewBinding(long dataStructureId, bool structured)
        {
            return PartialView("_dataStructuredStructurePreview", dataStructureId);
        }

        public ActionResult _dataStructureResultBinding(string searchTerms)
        {
            return PartialView("_datatructureSearchResult", searchTerms);
        }

        public ActionResult _createDataStructureBinding(long Id, string Name, string Description, bool isSructured, bool inUse, bool copy)
        {
            Name = Server.UrlDecode(Name);
            Description = Server.UrlDecode(Description);
            MessageModel DataStructureValidation = MessageModel.validateDataStructureInUse(Id);
            if (DataStructureValidation.hasMessage && DataStructureValidation.CssId == "0")
                return PartialView("_messageWindow", DataStructureValidation);        
            else
            {
                if (Id == 0)
                    return PartialView("_createDataStructure", new DataStructureCreateModel()
                    {
                        inUse = inUse
                    });
                else
                    return PartialView("_createDataStructure", new DataStructureCreateModel()
                    {
                        Id = Id,
                        Name = Name,
                        Description = Description,
                        isSructured = isSructured,
                        inUse = inUse,
                        copy = copy
                    });
            }

        }

        public ActionResult _deleteDataStructureBinding(long Id, string cssId)
        {
            return PartialView("_messageWindow", MessageModel.validateDataStructureDelete(Id));
        }

        public ActionResult createDataStructure(long Id, string Name, bool isStructured, string Description = "", string cssId = "", bool inUse = false)
        {
            Name = Server.UrlDecode(Name);
            Description = Server.UrlDecode(Description);
            MessageModel DataStructureValidation = storeDataStructure(Id, Name.Trim(), isStructured, Description.Trim(), cssId, inUse);
            return PartialView("_message", DataStructureValidation);
        }

        public MessageModel storeDataStructure(long Id, string Name, bool isStructured, string Description ="", string cssId = "", bool inUse = false)
        {
            Name = Server.UrlDecode(Name);
            Description = Server.UrlDecode(Description);
            MessageModel DataStructureValidation = MessageModel.validateDataStructureInUse(Id);
            if (DataStructureValidation.hasMessage && inUse == false)
            {
                return DataStructureValidation;
            }
            else
            {
                DataStructureValidation = MessageModel.validateDataStructureName(Id, Name, cssId);
                if (DataStructureValidation.hasMessage)
                {
                    return DataStructureValidation;
                }
                else
                {
                    DataStructureManager dataStructureManager = null;
                    try
                    {
                        dataStructureManager = new DataStructureManager();

                        DataStructure dataStructure;
                        if (isStructured)
                        {
                            if (Id == 0)
                            {
                                dataStructure = dataStructureManager.CreateStructuredDataStructure(Name.Trim(), Description.Trim(), null, null, DataStructureCategory.Generic);
                                LoggerFactory.LogData(dataStructure.Id.ToString(), typeof(DataStructure).Name, Vaiona.Entities.Logging.CrudState.Created);
                                return new MessageModel()
                                {
                                    Message = dataStructure.Id.ToString(),
                                    hasMessage = false,
                                    CssId = "redirect"
                                };
                            }
                            else
                            {
                                StructuredDataStructure StructuredDataStructure = dataStructureManager.StructuredDataStructureRepo.Get(Id);
                                StructuredDataStructure.Name = Name;
                                StructuredDataStructure.Description = Description;
                                dataStructure = dataStructureManager.UpdateStructuredDataStructure(StructuredDataStructure);
                                LoggerFactory.LogData(dataStructure.Id.ToString(), typeof(DataStructure).Name, Vaiona.Entities.Logging.CrudState.Created);
                                return new MessageModel()
                                {
                                    Message = Id.ToString(),
                                    hasMessage = false,
                                    CssId = "redirect"
                                };
                            }
                        }
                        else
                        {
                            if (Id == 0)
                            {
                                dataStructure = dataStructureManager.CreateUnStructuredDataStructure(Name.Trim(), Description.Trim());
                                LoggerFactory.LogData(dataStructure.Id.ToString(), typeof(DataStructure).Name, Vaiona.Entities.Logging.CrudState.Created);
                                return new MessageModel()
                                {
                                    Message = "refresh DataStructureResultGrid",
                                    hasMessage = false,
                                    CssId = "refresh"
                                };
                            }
                            else
                            {
                                UnStructuredDataStructure unStructuredDataStructure = dataStructureManager.UnStructuredDataStructureRepo.Get(Id);
                                unStructuredDataStructure.Name = Name;
                                unStructuredDataStructure.Description = Description;
                                dataStructure = dataStructureManager.UpdateUnStructuredDataStructure(unStructuredDataStructure);
                                LoggerFactory.LogData(dataStructure.Id.ToString(), typeof(DataStructure).Name, Vaiona.Entities.Logging.CrudState.Created);
                                return new MessageModel()
                                {
                                    Message = "refresh DataStructureResultGrid",
                                    hasMessage = false,
                                    CssId = "refresh"
                                };
                            }
                        }
                    }
                    finally
                    {
                        dataStructureManager.Dispose();
                    }
                }
            }
        }

        public ActionResult _validateDataStructureName(long Id, string Name , string cssId)
        {
            Name = Server.UrlDecode(Name);
            return PartialView("_message", MessageModel.validateDataStructureName(Id, Name, cssId));
        }

        public ActionResult copyDataStructure(long Id, bool isStructured, string Name = "", string Description = "", string cssId = "")
        {
            Name = Server.UrlDecode(Name);
            Description = Server.UrlDecode(Description);

            DataStructureManager dataStructureManager = null;
            MissingValueManager missingValueManager = null;
            try 
            {
                dataStructureManager = new DataStructureManager();
                missingValueManager = new MissingValueManager();

                if (!isStructured)
                {
                    UnStructuredDataStructure dataStructure = dataStructureManager.GetUnitOfWork().GetReadOnlyRepository<UnStructuredDataStructure>().Get(Id);
                    if (dataStructure != null)
                    {
                        if (Name == "")
                        {
                            Name = dataStructure.Name + " - Copy";
                        }

                        if (Description == "" && dataStructure.Description != null)
                        {
                            Description = dataStructure.Description;
                        }
                        LoggerFactory.LogCustom("Copy Data Structure" + Id);

Console/BExIS.Web.Shell/Areas/RPM/BExIS.Modules.Rpm.UI/old/Views/Shared/_createDataStructure.cshtml
@using BExIS.Modules.Rpm.UI.Models
@model DataStructureCreateModel

@{
    string Action = "";
    long validationId = 0;
    if (Model.copy)
    {
        if (Model.Id > 0)
        {
            Action = "copyDataStructure";
        }
        else
        {
            Action = "createDataStructure";
        }
        validationId = 0;
    }
    else
    {
        Action = "createDataStructure";
        validationId = Model.Id;
    }
}

<div class="bx-rpm-createDataStructureContainer" id="createDataStructureContainer">
    @Html.Hidden("id", Model.Id, new { @id = "id", @validationId = validationId })
    <table>
        <tr>
            <td>
                Name<span class="bx bx-required" title="Required"></span>
            </td>
            <td>
                <div title="The name will be used for a new Data Structure">@Html.TextBox("Name", Model.Name, new { @class = "bx-input", @id = "name", @autofocus="true" })</div>
                <div class="hidden bx-rpm-error" id="messageContainer"><span id="message" class="bx-rpm-message" value="none"></span></div>
            </td>
        </tr>
        <tr>
            <td>
                Description
            </td>
            <td>
                @Html.TextArea("Description", Model.Description, new { @class = "bx-input", @id = "description" })
            </td>
        </tr>
        <tr id="isSructuredContainer">
            <td>
                Data Format
            </td>
            <td class="bx-rpm-isSructured">
                @if (Model.Id > 0 || Model.inUse)
                {
                    if (!Model.isSructured)
                    {
                        <div>Tabular @Html.RadioButton("isSructured", true, new { @class = "true", @disabled = "true" })</div>
                                <div>File @Html.RadioButton("isSructured", false, new { @class = "false", @checked = "true", @disabled = "true" })</div>
                    }
                    else
                    {
                        <div>Tabular @Html.RadioButton("isSructured", true, new { @class = "true", @checked = "true", @disabled = "true" })</div>
                                <div>File @Html.RadioButton("isSructured", false, new { @class = "false", @disabled = "true" })</div>
                    }
                }
                else
                {
                    if (!Model.isSructured)
                    {
                        <div>Tabular @Html.RadioButton("isSructured", true, new { @class = "true" })</div>
                            <div>File @Html.RadioButton("isSructured", false, new { @class = "false", @checked = "true" })</div>
                    }
                    else
                    {
                        <div>Tabular @Html.RadioButton("isSructured", true, new { @class = "true", @checked = "true" })</div>
                            <div>File @Html.RadioButton("isSructured", false, new { @class = "false" })</div>
                    }
                }
            </td>
        </tr>
    </table>
    <table class="bx-footer" id="buttons">
        <tr>
            <td class="bx-footer left">
                @if (Model.Id > 0 && !Model.copy)
                {
                    if (Model.inUse)
                    {
                        <button class="bx-button action bx-disabled" id="deleteButton" disabled="true">Delete</button>
                    }
                    else
                    {
                        <button class="bx-button action" id="deleteButton" onclick="javascript:openDelWindow(@Model.Id,'@Server.UrlEncode(Model.Name)','datastructure')">Delete</button>
                    }
                }
            </td>
            <td class="bx-footer right">
                <button class="bx-button action" id="saveButton">Save</button>
                <button class="bx-button action" id="cancelButton">Cancel</button>
            </td>
        </tr>
    </table>   
</div>

<script type="text/javascript">
    var createDataStructureInUse = @Model.inUse.ToString().ToLower();

    $(function () {
        $('.bx-rpm-createDataStructureContainer #name').val(decodeURIComponent($('.bx-rpm-createDataStructureContainer #name').val()));
        $('.bx-rpm-createDataStructureContainer #description').val(decodeURIComponent($('.bx-rpm-createDataStructureContainer #description').val()));
    });

    $('.bx-rpm-createDataStructureContainer #saveButton').click(function () {
        var cssId = 'message';
        var parameters = '/?Id=' + $('.bx-rpm-createDataStructureContainer #id').val() + '&Name=' + encodeURIComponent($('.bx-rpm-createDataStructureContainer #name').val()) + '&Description=' + encodeURIComponent($('.bx-rpm-createDataStructureContainer #description').val()) + '&isStructured=' + $('.bx-rpm-createDataStructureContainer #isSructured:checked').val() + '&cssId=' + cssId + '&inUse=' + createDataStructureInUse;
        $.get('@Url.Action(Action, "DataStructureSearch", new { area = "RPM"} )' + parameters, function (data) {
            if ($(data).hasClass('bx-rpm-message') && $(data).attr('id') == cssId) {
                $(data).replaceAll('.bx-rpm-createDataStructureContainer #' + $(data).attr('id'));
                createWondowShowmessage();
            }
            else if ($(data).hasClass('bx-rpm-message') && $(data).attr('id') == 'redirect') {
                if( $('.bx-rpm-createDataStructureContainer #id').val() == '0' && createDataStructureInUse) {
                    if( $('.bx-rpm-dataStructure-container').length > 0){
                        $('.bx-rpm-dataStructure-functions #storeVariablesButton').attr('value', $(data).text())
                        $('.bx-rpm-dataStructure-functions #storeVariablesButton').trigger('click');
                    }
                }
                else{
                    window.location.href = "/RPM/DataStructureEdit?dataStructureId=" + $(data).text();
                }
            }
            else if ($(data).hasClass('bx-rpm-message') && $(data).attr('id') == 'refresh') {
                $("#windowCreate").data('tWindow').destroy();
                $("#bx-rpm-dataStructureResultGrid .t-refresh").trigger('click');
            }
        });
    });

    $('.bx-rpm-createDataStructureContainer #cancelButton').click(function () {
        $("#windowCreate").data('tWindow').destroy();
        if($("#bx-rpm-dataStructureResultGrid").lenght >0)
            $("#bx-rpm-dataStructureResultGrid .t-refresh").trigger('click');
    });

    //$('.bx-rpm-createDataStructureContainer #name').keyup(function () {
    //    createWondowValidateName('message');
    //});

    //$('.bx-rpm-createDataStructureContainer #name').change(function () {
    //    createWondowValidateName('message');
    //});

    //$('.bx-rpm-createDataStructureContainer #description').keyup(function () {
    //    createWondowShowmessage();
    //});

    //$('.bx-rpm-createDataStructureContainer #description').change(function () {
    //    createWondowShowmessage();
    //});

    function createWondowValidateName(cssId) {
        var parameters = encodeURI('/?Id=' + $('.bx-rpm-createDataStructureContainer #id').attr('validationId') + '&Name=' + encodeURIComponent($('.bx-rpm-createDataStructureContainer #name').val()) + '&cssId=' + cssId);
        $.get('@Url.Action("_validateDataStructureName", "DataStructureSearch", new { area = "RPM"} )' + parameters, function (data) {
            $(data).replaceAll('.bx-rpm-createDataStructureContainer #' + cssId);
            createWondowShowmessage();
        });
    }

    function createWondowShowmessage() {
        var hasMessage = false;
        for (var i = 0; i < $('.bx-rpm-createDataStructureContainer .bx-rpm-message').length; i++) {
            if ($('.bx-rpm-createDataStructureContainer .bx-rpm-message')[i].getAttribute('value').toLowerCase() == 'true') {
                hasMessage = true;
                break;
            }
            if ($('.bx-rpm-createDataStructureContainer .bx-rpm-message')[i].getAttribute('value').toLowerCase() == 'none') {
                hasMessage = 'none';
                break;
            }
        }

        if (hasMessage == true) {
            //$('.bx-rpm-createDataStructureContainer #saveButton').attr('disabled', 'disabled');
            $(".bx-rpm-createDataStructureContainer #messageContainer").removeClass('hidden');
            //$('.bx-rpm-createDataStructureContainer #saveButton').addClass('bx-disabled');
        }
        else if(hasMessage == false){
            //$('.bx-rpm-createDataStructureContainer #saveButton').removeAttr('disabled');
            $(".bx-rpm-createDataStructureContainer #messageContainer").addClass('hidden');
            //$('.bx-rpm-createDataStructureContainer #saveButton').removeClass('bx-disabled');
        }
    }

    function openDelWindow(id, name, type) {
        if ($("#windowCreate").length > 0) {
            $("#windowCreate").toggle('fast');
        }
        var parameters = '/?Id=' + id;
        $.ajax({
            type: 'GET',
            url: '@Url.Action("_deleteDataStructureBinding", "DataStructureSearch")' + parameters,
            dataType: 'html',
            success: function (data) {
                createMessageWindow(data, 'Delete DataStructure ' + name + ' (' + id + ')', type, id);
            }
        });
    }
</script>

Console/BExIS.Web.Shell/Areas/RPM/BExIS.Modules.Rpm.UI/old/Views/Shared/_domainConstraintView.cshtml
@model BExIS.Modules.Rpm.UI.Models.DomainConstraintModel

@using BExIS.Modules.Rpm.UI.Helpers;
@using BExIS.Modules.Rpm.UI.Models;

@using (Html.BeginCollectionItem("DomainConstraints"))
{ 
    <table class="bx-rpm-container bx-rpm-constrainTable" id="domainConstraint_@Model.Id">
        <tr>
            <td class="bx-rpm-constrainlabel">
                Domain
                @Html.HiddenFor(m=>m.Id, new { @id= "domain_id" })
            </td>
            <td class="bx-rpm-negated">
                <!--Negated-->
                <div class="bx-rpm-container">
                    <div class="bx-rpm-label">@Html.Label("invert")</div>
                    @Html.CheckBoxFor(m => m.Negated, new { @id = "domain_invert", onclick = "javascript:onPatternChange()" })
                </div>
            </td>
            <td class="bx-rpm-constrainValue">
                <div class="bx-rpm-container">
                    <div class="bx-rpm-label">@Html.Label("Terms")</div>
                    @Html.TextBoxFor(m => m.Terms, new {@id = "domain_terms", onkeyup = "javascript:onDomainChange()", onchange = "javascript:onDomainChange()" })
                </div>
                <div class="bx-function bx-info bx-disabled" title="@Model.FormalDescription" id="domain_FormalDescription"></div>
            </td>
            <td class="bx-rpm-constrainDesc">
                <div class="bx-rpm-container">
                    <div class="bx-rpm-label">@Html.Label("Description")</div>
                    @Html.TextBoxFor(m => m.Description, new { id = "domain_desc" })
                </div>
            </td>
            <td>
                <div>
                    <a class="bx bx-grid-function  bx-eraser" onclick="resetDomain(this)" id="@Model.Id" title="Erase Constraint"></a>
                </div>
            </td>
        </tr>
    </table>
}

<script type="text/jscript">

</script>

@*<script>

    $("#addDomainItem").unbind().click(function () {

    
        $.ajax({
            url: this.href,
            cache: false,
            success: function (html) { $("#domainItems").append(html); }
        });

        return false;
    });

    $("a.removeDomainItem").live("click", function () {
        $(this).parents("div.domainItem:first").remove();
        return false;
    });

</script>*@

Console/BExIS.Web.Shell/Areas/RPM/BExIS.Modules.Rpm.UI/old/Views/Shared/_message.cshtml
@model BExIS.Modules.Rpm.UI.Models.MessageModel

<span class="bx-rpm-message" id="@Model.CssId" value ="@Model.hasMessage">@Model.Message</span>

Console/BExIS.Web.Shell/Areas/RPM/BExIS.Modules.Rpm.UI/old/Views/Shared/_messageWindow.cshtml
@model BExIS.Modules.Rpm.UI.Models.MessageModel

@{ 
    string[] lines = Model.Message.Split('\n');
}

@if (!Model.hasMessage)
{
    <div class="bx-rpm-message" value="@Model.hasMessage" id="@Model.CssId">
        @Model.Message
        <div id="buttons">
            <button class="bx-button small function" onclick="messageWindowYes(@Model.CssId)" id="yesButton">Yes</button>
            <button class="bx-button small function" onclick="messageWindowCancel(@Model.CssId)" id="noButton">No</button>
        </div>
    </div>
}
else if (Model.hasMessage)
{
    <div class="bx-rpm-message" value="@Model.hasMessage" id="@Model.CssId">
        @foreach(string s in lines)
        {
            @s<br />
        }
        <div id="buttons">
            <button class="bx-button small function" onclick="messageWindowCancel(@Model.CssId)" id="okButton">OK</button>
        </div>
    </div>
}

Console/BExIS.Web.Shell/Areas/RPM/BExIS.Modules.Rpm.UI/old/Views/Shared/_patternConstraintView.cshtml
@model BExIS.Modules.Rpm.UI.Models.PatternConstraintModel

@using BExIS.Modules.Rpm.UI.Helpers;

@using (Html.BeginCollectionItem("PatternConstraints"))
{ 
    <table class="bx-rpm-container bx-rpm-constrainTable" id="patternConstraint_@Model.Id">
        <tr>
            <td class="bx-rpm-constrainlabel">
                Pattern
                @Html.HiddenFor(m=>m.Id, new { @id= "pattern_id" })
            </td>
            <td class="bx-rpm-negated">
                <div class="bx-rpm-container">
                    <div class="bx-rpm-label">@Html.Label("invert")</div>
                    <!--Negated-->
                    @Html.CheckBoxFor(m => m.Negated, new { @id = "pattern_invert", onclick = "javascript:onPatternChange()" })
                </div>
            </td>
            <td class="bx-rpm-constrainValue">
                <div class="bx-rpm-container">
                    <div class="bx-rpm-label">@Html.LabelFor(m=>m.MatchingPhrase)</div>
                    @Html.TextBoxFor(m=>m.MatchingPhrase, new { @id = "pattern_phrase", onkeyup = "javascript:onPatternChange()", onchange = "javascript:onPatternChange()" })
                </div>
                <div class="bx-function bx-info bx-disabled" title="@Model.FormalDescription" id="pattern_FormalDescription"></div>
            </td>
            <td class="bx-rpm-constrainDesc">
                <div class="bx-rpm-container">
                    <div class="bx-rpm-label">@Html.Label("Description")</div>
                    @Html.TextBoxFor(m => m.Description, new { id= "pattern_desc" })
                </div>
            </td>
            <td>
                <div>
                    <a class="bx bx-grid-function bx-eraser" onclick="restPattern(this)" id="@Model.Id" title="Erase Constraint"></a>
                </div>
            </td>
        </tr>
    </table>
}
<script type="text/jscript">

</script>

Console/BExIS.Web.Shell/Areas/RPM/BExIS.Modules.Rpm.UI/old/Views/Shared/_rangeConstraintView.cshtml
@model BExIS.Modules.Rpm.UI.Models.RangeConstraintModel

@using BExIS.Modules.Rpm.UI.Helpers;

@using (Html.BeginCollectionItem("RangeConstraints"))
{ 
<table class="bx-rpm-container bx-rpm-constrainTable" id="rangeConstraint_@Model.Id">
    <tr>
        <td class="bx-rpm-constrainlabel">
            Range
            @Html.HiddenFor(m => m.Id, new { @id = "range_id" })
        </td>
        <td class="bx-rpm-negated">
            <!--Negated-->
            <div class="bx-rpm-container bx-rpm-checkbox">
                <div class="bx-rpm-label">@Html.Label("invert")</div>
                @Html.CheckBoxFor(m => m.Negated, new { @id = "range_invert", onclick = "javascript:onRangeChange()" })
            </div>
        </td>
        <td class="bx-rpm-constrainValue">
            <div class="bx-rpm-container">
                <div class="bx-rpm-label">@Html.LabelFor(m => m.Min)</div>
                @Html.TextBoxFor(m => m.Min, new { @id = "range_min", onkeyup = "javascript:onRangeChange()", onchange = "javascript:onRangeChange()" })
                <div class="bx-errorMsg">@Html.ValidationMessageFor(m => m.Min)</div>
            </div>
            <div class="bx-rpm-container bx-rpm-checkbox">
                <div class="bx-rpm-label bx-rpm-include">@Html.Label("include")</div>
                @Html.CheckBoxFor(m => m.MinInclude, new { @id = "range_mininclude", onclick = "javascript:onRangeChange()" })
            </div>
            <div class="bx-rpm-container">
                <div class="bx-rpm-label">@Html.LabelFor(m => m.Max)</div>
                @Html.TextBoxFor(m => m.Max, new { @id = "range_max", onkeyup = "javascript:onRangeChange()", onchange = "javascript:onRangeChange()" })
                <div class="bx-errorMsg">@Html.ValidationMessageFor(m => m.Max)</div>
            </div>
            <div class="bx-rpm-container bx-rpm-checkbox">
                <div class="bx-rpm-label bx-rpm-include">@Html.Label("include")</div>
                @Html.CheckBoxFor(m => m.MaxInclude, new { @id = "range_maxinclude", onclick = "javascript:onRangeChange()" })
            </div>
            <div class="bx-function bx-info bx-disabled" id="range_FormalDescription" title="@Model.FormalDescription"></div>
            <div id="errorMsg" class="hidden"><span class="bx-errorMsg .bx-rpm-message" id="errorMsgText"></span></div>
        </td>
        <td class="bx-rpm-constrainDesc">
            <div class="bx-rpm-container">
                <div class="bx-rpm-label">@Html.Label("Description")</div>
                @Html.TextBoxFor(m => m.Description, new { id = "range_desc" })
            </div>
        </td>
        <td>
            <div>
                <a class="bx bx-grid-function  bx-eraser" onclick="javascript:restRange(this)" id="@Model.Id" title="Erase Constraint"></a>
            </div>
        </td>
    </tr>
</table>
}

<script type="text/jscript">
   
</script>